# Generated by Django 6.0.6 on 2026-06-26 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assettracker', '0005_inventoryitem_remove_asset_asset_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetrequest',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='assetrequest',
            name='to_date',
        ),
        migrations.RemoveField(
            model_name='assetrequest',
            name='total_days',
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
