# Generated by Django 6.0.6 on 2026-06-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assettracker', '0006_remove_assetrequest_from_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
